language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libqt4-dev qt4-qmake ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install qtcreator      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install mingw      ; fi

script:
  - qmake
  - make

compiler:
  - gcc

os:
  - linux
  - windows
  - osx
