image: macos-monterey

install:
  - brew update
#  - brew upgrade
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install qt@6
#  - export QTDIR=/usr/local/Cellar/qt/6.*
#  - export PATH="${PATH}:${QTDIR}/bin"

build_script:
  - qmake APP_VERSION="${APPVEYOR_REPO_TAG_NAME}"
  - make -j $(nproc)
  - macdeployqt von-neumann-emu.app -dmg

after_build:
  - appveyor PushArtifact "von-neumann-emu.dmg"
  - sh: |
      if [ "$APPVEYOR_REPO_TAG" = "true" ] ; then
        macdeployqt von-neumann-emu.app -dmg
        mv von-neumann-emu.dmg "emulator-${APPVEYOR_REPO_TAG_NAME}-macos-x86_64.dmg"
        appveyor PushArtifact "emulator-${APPVEYOR_REPO_TAG_NAME}-macos-x86_64.dmg"
      fi

#on_finish:
#  - sh: export APPVEYOR_VNC_BLOCK=true
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -

deploy:
  - release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'von-Neumann-Emulator $(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub
    auth_token:
      secure: PL44es3rGKnzlt+xc0ZcUSqy/81+fxqB+LAgbKUc2pULxR8cV5zKLvcvbvxGp36u
    artifact: /emulator-.*\.dmg/
    draft: false
    prerelease: false
    tag: $(APPVEYOR_REPO_TAG_NAME)
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
